# Generated by Django 6.0.5 on 2026-05-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'Заказчик'), ('builder', 'Подрядчик'), ('supplier', 'Поставщик'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('phone', models.CharField(blank=True, max_length=128, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meter', 'Прибор'), ('sensor', 'Датчик'), ('boiler', 'Котел'), ('valve', 'Арматура'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('passport_scan', models.FileField(blank=True, upload_to='equipment_passports/', verbose_name='Скан паспорта')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opo', models.BooleanField(default=False, verbose_name='ОПО')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('checking_frequency', models.CharField(blank=True, max_length=100, verbose_name='Периодичность проверки')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_as_contractor', to='registry.contractor', verbose_name='Контрагент')),
                ('responsible_from_builder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_as_builder_responsible', to='registry.contractor', verbose_name='Ответственный от подрядчика')),
                ('responsible_from_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_as_client_responsible', to='registry.contractor', verbose_name='Ответственный от клиента')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=100, verbose_name='Регистрационный номер')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registry.siteobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Регистрация объекта',
                'verbose_name_plural': 'Регистрации объектов',
                'ordering': ['-issued_at', 'reg_number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contract', 'Договор'), ('act', 'Акт'), ('invoice', 'Счет'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ежемесячно')),
                ('onetime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Разово')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('courier', 'Курьер'), ('pickup', 'Самовывоз'), ('edo', 'ЭДО'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Способ доставки')),
                ('file', models.FileField(blank=True, upload_to='documents/', verbose_name='Файл документа')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.siteobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ObjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.equipment', verbose_name='Оборудование')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.siteobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Оборудование объекта',
                'verbose_name_plural': 'Оборудование объектов',
                'unique_together': {('object', 'equipment')},
            },
        ),
    ]
