# Generated by Django 6.0.5 on 2026-05-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='checking_frequency',
            field=models.CharField(blank=True, max_length=100, verbose_name='Периодичность поверки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('meter', 'Прибор'), ('sensor', 'Датчик'), ('boiler', 'Котел'), ('valve', 'Клапан'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип'),
        ),
    ]
