# Generated by Django 6.0.5 on 2026-05-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_equipment_checking_frequency_alter_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteobject',
            name='checking_frequency',
        ),
    ]
