# Generated by Django 6.0.5 on 2026-05-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_siteobject_checking_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.RemoveField(
            model_name='document',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='monthly',
        ),
        migrations.RemoveField(
            model_name='document',
            name='onetime',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('contract', 'Договор'), ('act', 'Акт'), ('passport', 'Паспорт'), ('certificate', 'Сертификат'), ('protocol', 'Протокол'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='registry.document', verbose_name='Документ')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
