# Generated by Django 6.0.5 on 2026-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_document_options_remove_document_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={},
        ),
        migrations.AddField(
            model_name='contractor',
            name='contact_persons',
            field=models.TextField(blank=True, default='', verbose_name='Контактные лица'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='type',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('contractor', 'Подрядчик'), ('supplier', 'Поставщик'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
