# Generated by Django 6.0.5 on 2026-07-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_siteobject_contractor_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней поверки'),
        ),
    ]
