server {
    listen 80;
    server_name 161.104.33.28;

    client_max_body_size 20M;

    location /static/ {
        alias /srv/sss/staticfiles/;
    }

    location /media/ {
        alias /srv/sss/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/srv/sss/sss.sock;
    }
}
